# Generated by Django 3.2.10 on 2022-01-07 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappdjf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('c_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappdjf.c_emploi')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappdjf.visiteur')),
            ],
        ),
        migrations.CreateModel(
            name='LangueMaitrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=100)),
                ('c_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappdjf.c_emploi')),
            ],
        ),
        migrations.CreateModel(
            name='AnnoncesEpingles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappdjf.travail')),
            ],
        ),
    ]
