# Generated by Django 3.2.10 on 2022-01-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0002_annoncesepingles_languemaitrise_notes_visiteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languemaitrise',
            name='niveau',
            field=models.CharField(max_length=400),
        ),
    ]
