# Generated by Django 3.2.10 on 2022-01-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0003_alter_languemaitrise_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_emploi',
            name='adresse',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='c_emploi',
            name='description',
            field=models.TextField(default='', editable=False, max_length=400),
        ),
        migrations.AddField(
            model_name='c_emploi',
            name='experience',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='c_emploi',
            name='skills',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
