# Generated by Django 3.2.11 on 2022-01-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0004_auto_20220112_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', editable=False, max_length=100)),
                ('utilite', models.CharField(max_length=15)),
                ('description', models.TextField(default='', editable=False, max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='AnnoncesEpingles',
        ),
    ]
