# Generated by Django 3.2.11 on 2022-01-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0005_auto_20220123_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='languemaitrise',
            name='langue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myappdjf.langue'),
        ),
    ]
