# Generated by Django 3.2.11 on 2022-01-31 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0006_languemaitrise_langue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langue',
            name='utilite',
        ),
    ]
